language: go

go:
  - "1.10"

install:
  - go get github.com/golang/dep/cmd/dep
  - dep init -v

script:
  - ls -lR

after_script:
  - git config user.name "wwcd"
  - git config user.email "shoulinwang@gmail.com"
  - git add Gopkg.* vendor
  - git commit -m "Update vendor"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

