language: go

go:
  - "1.10"


install:
  - go get github.com/golang/dep/cmd/dep
  - go checkout master
  - dep init -v

script:
  - ls -lR

after_script:
  - git config user.name "wwcd"
  - git config user.email "shoulinwang@gmail.com"
  - git add Gopkg.* vendor
  - git commit -m "Update vendor"
  - git push --force "https://${GH_TOKEN}@github.com/wwcd/depinitbytravisci" master:master

